require(readxl)
require(jsonlite)
require(ggmap)
require(plyr)
require(tidyr)
require(dplyr)
require(tidyr)
require(stringr)
require(chorddiag)
require(lubridate)
require(data.table)
require(openxlsx)
require(rmarkdown)
require(rmdformats)
require(thematic)
require(tictoc)
require(bslib)
require(formattable)
require(sparkline)
require(kableExtra)   # tabele
require(collapse)
require(arules)       # reguły asocjacyjne
require(arulesViz)    # wizualizacja reguł
require(archive)      # pakowanie plików
require(DT)
require(gt)
require(gtExtras)
require(ggpubr)
require(bookdown)
require(here)
require(scales)
require(stringi)
library(patchwork)
library(reticulate)